<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Issues extends \App\Entities\Issues implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'projectId', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'title', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'estTime', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'parentIssueId', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'createdOn', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'createdBy', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'updatedBy', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'updatedOn', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'category', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'priority', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'resolution', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'issueType', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'assignedTo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'id', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'projectId', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'title', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'description', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'estTime', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'status', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'parentIssueId', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'createdOn', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'createdBy', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'updatedBy', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'updatedOn', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'category', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'priority', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'resolution', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'issueType', '' . "\0" . 'App\\Entities\\Issues' . "\0" . 'assignedTo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Issues $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectId($projectId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectId', [$projectId]);

        return parent::setProjectId($projectId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectId', []);

        return parent::getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstTime($estTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstTime', [$estTime]);

        return parent::setEstTime($estTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstTime', []);

        return parent::getEstTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentIssueId($parentIssueId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentIssueId', [$parentIssueId]);

        return parent::setParentIssueId($parentIssueId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentIssueId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentIssueId', []);

        return parent::getParentIssueId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn($updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\App\Entities\Categories $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriority(\App\Entities\Priorities $priority = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriority', [$priority]);

        return parent::setPriority($priority);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriority', []);

        return parent::getPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setResolution(\App\Entities\IssueResolutionTypes $resolution = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResolution', [$resolution]);

        return parent::setResolution($resolution);
    }

    /**
     * {@inheritDoc}
     */
    public function getResolution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResolution', []);

        return parent::getResolution();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssueType(\App\Entities\IssueTypes $issueType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssueType', [$issueType]);

        return parent::setIssueType($issueType);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssueType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssueType', []);

        return parent::getIssueType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignedTo(\App\Entities\Users $assignedTo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignedTo', [$assignedTo]);

        return parent::setAssignedTo($assignedTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignedTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignedTo', []);

        return parent::getAssignedTo();
    }

}
