<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class IssueActivity extends \App\Entities\IssueActivity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'id', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'issueId', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'userId', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'startTime', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'stopTime', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'secondsElapsed'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'id', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'issueId', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'userId', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'startTime', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'stopTime', '' . "\0" . 'App\\Entities\\IssueActivity' . "\0" . 'secondsElapsed'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (IssueActivity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssueId($issueId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssueId', [$issueId]);

        return parent::setIssueId($issueId);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssueId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssueId', []);

        return parent::getIssueId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartTime($startTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartTime', [$startTime]);

        return parent::setStartTime($startTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartTime', []);

        return parent::getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setStopTime($stopTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStopTime', [$stopTime]);

        return parent::setStopTime($stopTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getStopTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStopTime', []);

        return parent::getStopTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecondsElapsed($secondsElapsed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecondsElapsed', [$secondsElapsed]);

        return parent::setSecondsElapsed($secondsElapsed);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecondsElapsed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecondsElapsed', []);

        return parent::getSecondsElapsed();
    }

}
